#!/bin/bash
#
# install
#
# eric o meehan
# 2022-05-24
#
# adds this policy to a given installation

POLICY_ID=policy-template

function log() {
	priority=${2:-6}
	executable=$(cd $(dirname $0) && pwd)/$0
	[[ $syslogServer != 0 ]] && syslogServerArg="-n $syslogServer --tcp"
	tag="executable={{ $executable }} | executionId={{ $executionId }}"
	logger -p $priority $t "$tag" $syslogServerArg "$1"
}

while [[ $# -gt 0 ]]
do
	case $1 in
		-e|--executionId)
			executionId=$2
			shift ; shift ;;
		-g|--groupId)
			groupId=$2
			shift ; shift ;;
		-i|--installationId)
			installationId=$2
			shift ; shift ;;
		-s|--syslogServer)
			syslogServer=$2
			shift ; shift ;;
		-u|--userId)
			userId=$2
			shift ; shift ;;
		*)
			echo "invalid argument: $1" >&2
			exit 1 ;;
	esac
done
[[ -z $executionId ]] && executionId=$(uuidgen)
[[ -z $groupId ]] && groupId=0
[[ -z $syslogServer ]] && syslogServer=0
[[ -z $userId ]] && userId=0
if [[ -z $installationId ]]
then
	log "argument required | argument={{ installationId }}" 3
	log "exiting" 3
	exit 1
fi

if [[ $groupId == 0 ]]
then
	if [[ $userId == 0 ]]
	then
		policySource=/usr/local/src/$installationId/policies/$POLICY_ID
	else
		policySource=/usr/local/src/$installationId/users/$userId/policies/$POLICY_ID
	fi
else
	if [[ $userId == 0 ]]
	then
		policySource=/usr/local/src/$installationId/groups/$groupId/policies/$POLICY_ID
	else
		policySource=/usr/local/src/$installationId/groups/$groupId/users/$userId/policies/$POLICY_ID
	fi
fi

log "begin"
log "installing policy | policyId={{ $POLICY_ID }}"

# ...
